### ISSUE TITLE
Diablo 2 COF animation drawing order

### ISSUE THREAD

**Issue by ghost** [dgengin/DGEngine#28]
Diablo 2's COF animations aren't drawing the shield in the right order.

![Diablo 2 sorceress](https://user-images.githubusercontent.com/20025614/62322411-efa55b00-b49c-11e9-84dc-618f4319c905.png)
![Diablo 2 sorceress 2](https://user-images.githubusercontent.com/20025614/62322583-4448d600-b49d-11e9-9213-0fc0824b8181.png)

This is either a bug in my COF decoder, or in the texturePack order in the configuration files for each player:

https://github.com/dgengin/DGEngine/blob/master/gamefilesd2/level/player/Sorceress/textures.json

This issue is to track the proper way to draw all of the COF animations of Diablo 2.

Can COF file layers be missing and be skipped when drawing (for instance, if the shield isn't equipped, you use a COF with a shield, but don't draw that layer)?

The order of the layers in the COF file isn't always the same, does this affect drawing?

I'm assuming the layers should be loaded in this order:
`HD, TR, LG, RA, LA, RH, LH, SH, S1, S2, S3, S4, S5, S6, S7, S8`
And then the order indexes apply to these.

**Comment by grantramsay** [comment]
Before I start looking at DT1/DS1 tiles and forget:

The COF layers not showing correctly is just the direction mapping.
COFs directions are mapped differently to DCCs (they are simple clockwise from down/South).

Replace [this line](https://github.com/dgengin/DGEngine/blob/master/src/CompositeTexture.cpp#L123) in CompositeTexture.cpp with below for a quick demo/test of it working:

    // Re-map COFs directions.
    for (int cofDirection = 0; cofDirection < header.directions; cofDirection++)
    {
        int newDirection = cofDirection;
        // TODO: 8 and 32 directions
        if (header.directions == 16)
        {
            // Re-map COF to DCC directions.
            // directionTable is similar to reverse getNormalizedDirection() function
            static const uint8_t directionTable[16] = {
                4, 8, 0, 9, 5, 10, 1, 11, 6, 12, 2, 13, 7, 14, 3, 15 };
            newDirection = directionTable[cofDirection];
        }

        int len = header.frames * header.layers;
        int destIdx = layersOrdersStartIdx + newDirection * len;
        fileStream.read((uint8_t*)layersOrders.data() + destIdx, len);
    }
Just an example, you might want to implement it in a different way

(Edited for correctness as per following messages)

**Comment by ghost** [comment]
I tested and it works.

Isn't the order of the COF drawing indexes the same as the order of the DCC files?

What I did was to get a range from an index. I would think that geting a range and getting the drawing order based on that should work.

**Comment by grantramsay** [comment]
Sorry I was wrong about the DCC having a different only 8 directions, they both have 16 but the direction mapping is different to COF. Also should've been "clockwise" in previous comment...

I made a table to show the order (ignore bad COF in images, images are only to show DCC direction), things to note in the table:
- The first 8 COFs all have RightArm drawn first (i.e. at the bottom layer of the image), yet the first 8 DCC images contain a full rotation of the player. This is a giveaway that the COF direction is ordered by rotation, and different to DCC order.
- Drawing order of the shield. E.g. DCC Direction 2 is what failed for your sorceress above. That's because shield is drawn last (on top) of everything, but with the re-mapped COF it is drawn 2nd (near the bottom layer).

DCC Direction | DCC image | COF (BANUHTH.COF) | Re-mapped COF
| --- | --- | --- | --- |
0 | <img width="122" alt="0" src="https://user-images.githubusercontent.com/8636545/63355184-076a5380-c366-11e9-8f48-9b81300f4bf8.png"> | RightArm Legs Torso LeftArm Special1 Head Special2 Shield | RightArm Legs Torso LeftArm Special1 Head Special2 Shield
1 | <img width="122" alt="1" src="https://user-images.githubusercontent.com/8636545/63355199-0df8cb00-c366-11e9-9525-3ba5bef55026.png"> | RightArm Legs Torso LeftArm Special1 Head Special2 Shield | RightArm Legs Torso LeftArm Special1 Head Special2 Shield
2 | <img width="122" alt="2" src="https://user-images.githubusercontent.com/8636545/63355233-1cdf7d80-c366-11e9-91f7-008b05334bc9.png"> | RightArm Legs Torso LeftArm Special1 Head Special2 Shield | Legs Shield LeftArm Torso RightArm Special2 Head Special1
3 | <img width="122" alt="3" src="https://user-images.githubusercontent.com/8636545/63355256-2537b880-c366-11e9-8722-cfcf21d8503a.png"> | RightArm Legs Torso LeftArm Special1 Head Special2 Shield | Legs Shield LeftArm Torso RightArm Special2 Head Special1
4 | <img width="122" alt="4" src="https://user-images.githubusercontent.com/8636545/63355262-2a950300-c366-11e9-961e-47ffa2c71082.png"> | RightArm Legs Torso LeftArm Special1 Head Special2 Shield | RightArm Legs Torso LeftArm Special1 Head Special2 Shield
5 | <img width="122" alt="5" src="https://user-images.githubusercontent.com/8636545/63355272-2e288a00-c366-11e9-85a9-f798f809229c.png"> | RightArm Legs Torso LeftArm Special1 Head Special2 Shield | RightArm Legs Torso LeftArm Special1 Head Special2 Shield
6 | <img width="122" alt="6" src="https://user-images.githubusercontent.com/8636545/63355291-3385d480-c366-11e9-942c-e3cd53b2c3d2.png"> | RightArm Legs Torso LeftArm Special1 Head Special2 Shield | Shield LeftArm Legs Torso RightArm Special2 Head Special1
7 | <img width="122" alt="7" src="https://user-images.githubusercontent.com/8636545/63355305-38e31f00-c366-11e9-81d1-b595e240b15d.png"> | RightArm Legs Shield Torso LeftArm Special1 Head Special2 | Legs Shield LeftArm Torso RightArm Special2 Head Special1
8 | <img width="122" alt="8" src="https://user-images.githubusercontent.com/8636545/63355315-3d0f3c80-c366-11e9-9b40-94955fff0117.png"> | Shield LeftArm Legs Torso RightArm Special2 Head Special1 | RightArm Legs Torso LeftArm Special1 Head Special2 Shield
9 | <img width="122" alt="9" src="https://user-images.githubusercontent.com/8636545/63355330-41d3f080-c366-11e9-825b-0fc8ae2d963e.png"> | Shield LeftArm Legs Torso RightArm Special2 Head Special1 | RightArm Legs Torso LeftArm Special1 Head Special2 Shield
10 | <img width="122" alt="10" src="https://user-images.githubusercontent.com/8636545/63355375-4dbfb280-c366-11e9-88ec-552103d8d707.png"> | Legs Shield LeftArm Torso RightArm Special2 Head Special1 | RightArm Legs Torso LeftArm Special1 Head Special2 Shield
11 | <img width="122" alt="11" src="https://user-images.githubusercontent.com/8636545/63355387-53b59380-c366-11e9-8ac2-dd34d9c4efb0.png"> | Legs Shield LeftArm Torso RightArm Special2 Head Special1 | RightArm Legs Shield Torso LeftArm Special1 Head Special2
12 | <img width="122" alt="12" src="https://user-images.githubusercontent.com/8636545/63355396-587a4780-c366-11e9-8268-ce28e1c1ad99.png"> | Legs Shield LeftArm Torso RightArm Special2 Head Special1 | Shield LeftArm Legs Torso RightArm Special2 Head Special1
13 | <img width="122" alt="13" src="https://user-images.githubusercontent.com/8636545/63355412-5f08bf00-c366-11e9-947b-cb13a0f8194e.png"> | Legs Shield LeftArm Torso RightArm Special2 Head Special1 |  Legs Shield LeftArm Torso RightArm Special2 Head Special1
14 | <img width="122" alt="14" src="https://user-images.githubusercontent.com/8636545/63355425-6334dc80-c366-11e9-94bc-63409065514c.png"> |  Legs Shield LeftArm Torso RightArm Special2 Head Special1 | Legs Shield LeftArm Torso RightArm Special2 Head Special1
15 | <img width="122" alt="15" src="https://user-images.githubusercontent.com/8636545/63355443-6a5bea80-c366-11e9-8731-10ef7a2b66e9.png"> |  Legs Torso LeftArm RightArm Special1 Special2 Shield Head |  Legs Torso LeftArm RightArm Special1 Special2 Shield Head

**Comment by ghost** [comment]
Final question, does this re-mapping apply to all COFs or are there exceptions? Such as a 16 direction COF file where the order would be wrong with the re-ordering.

**Comment by grantramsay** [comment]
AFAIK it applies to all COFs.
8 and 32 directional COFs will also need to be mapped in a similar fashion

**Comment by ghost** [comment]
Where can I see what the 8 and 32 direction mapping array would be like so as to do both. Sometime in the future I plan on supporting more directions when moving the player.

**Comment by grantramsay** [comment]
16 (from above):

    static const uint8_t directionTable[16] = {
            4, 8, 0, 9, 5, 10, 1, 11, 6, 12, 2, 13, 7, 14, 3, 15 };

8 would just be every second value (e.g. similar to your `getNormalizedDirection()` func):

    static const uint8_t directionTable[8] = {
            4, 0, 5, 1, 6, 2, 7, 3 };

My guess for extrapolating that to 32 would be to insert values 16 -> 31 in every 2nd spot:

    static const uint8_t directionTable[32] = {
            4, 16, 8, 17, 0, 18, 9, 19, 5, 20, 10, 21, 1, 22, 11, 23, 6, 24, 12, 25, 2, 26, 13, 27, 7, 28, 14, 29, 3, 30, 15, 31 };

Disclaimer: I could be wrong (I'll see if I can find a 32 directional texture and double check...)

**Comment by grantramsay** [comment]
With my quick look I couldn't find any 32 directional COF files :/
I had a dig though Riiablo and [found what look to be equivalent (but reverse) translations](https://github.com/collinsmith/riiablo/blob/abdaa45db011b33723589787ff9934e46d6e5ba3/core/src/com/riiablo/codec/DC.java#L122), so I'd say the above is likely correct

**Comment by ghost** [comment]
fixed in 5667905
